### ISSUE TITLE
Bug on link rules documentation

### ISSUE THREAD

**Issue by alvaroaxsmith** [yeonjuan/html-eslint#117]
### Link redirecting incorrectly on https://yeonjuan.github.io/html-eslint/docs/getting-started/

<br>

<br>

### Bug Input
![image](https://user-images.githubusercontent.com/69737979/207458807-a269eb8f-5ae6-471d-add0-57d4a169cf11.png)

<br>

<br>

### Bug Output
![image](https://user-images.githubusercontent.com/69737979/207457922-1cef52b9-6a43-4556-bcc7-4c111f643b0b.png)

<br>

<br>

### Correct Output
![image](https://user-images.githubusercontent.com/69737979/207458408-8fcf9e44-e53a-4f8a-b143-f36ffe41352a.png)

**Comment by yeonjuan** [comment]
@alvaroaxsmith Thanks for the reporting issue!. I'll fix it 👍
