### ISSUE TITLE
Ignore angular attributes

### ISSUE THREAD

**Issue by splincode** [yeonjuan/html-eslint#134]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/12021443/231953462-677faffc-c68e-4398-9623-15756156c555.png">

But I can use `[attr.alt]` or `[alt]` in angular

**Comment by yeonjuan** [comment]
Hi @splincode Thanks for the reporting! I never thought of using this project for angular.
Maybe we can support it by implementing options like the ones below.
i.e 

```
{
   "@html-eslint/require-img-alt": ["error", {
          "substitute": ["[attr.alt]", "[alt]"]
     }],
}
```

**Comment by splincode** [comment]
great idea
