### ISSUE TITLE
Add release notes

### ISSUE THREAD

**Issue by jdussouillez** [yeonjuan/html-eslint#147]
I'm starting to use this and it works great, thanks!

But I think it lacks a changelog or release notes file (or using Github milestones). It's hard to know what changed when updating to a new version (new rules, breaking changes, etc).

**Comment by yeonjuan** [comment]
Hi @jdussouillez. I agree. Thanks for the suggestion!
It would be nice to automate the recording of information about changes in [GitHub releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release). To accomplish this, To accomplish this, I think the following tasks should be accomplished. If you know of any good ideas or tools, I'd love to hear about them.
- [ ] Add convention for commit messages or PR messages and check the convention in Github action.
  - https://www.conventionalcommits.org/en/v1.0.0/ 
- [ ] Automated release notes
  - https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

**Comment by jdussouillez** [comment]
> If you know of any good ideas or tools, I'd love to hear about them

I use Conventional Commits but I don't use auto generated release notes in Github.

Tip: I use a Git hook to prevent myself from committing invalid messages (in complement of the Github action check): https://github.com/conventional-changelog/commitlint#add-hook

**Comment by yeonjuan** [comment]
Hi @jdussouillez I made first release note, and we'll be writing one for every release going forward. Thank you. see https://github.com/yeonjuan/html-eslint/releases
