### ISSUE TITLE
Add support for eslint flat config

### ISSUE THREAD

**Issue by TheElegantCoding** [yeonjuan/html-eslint#174]
- https://eslint.org/docs/latest/use/configure/configuration-files-new
- https://eslint.org/docs/latest/use/configure/migration-guide#start-using-flat-config-files

**Comment by yeonjuan** [comment]
Hi @TheElegantCoding, Thanks for the report!. Is there anything else we need to do to support flat config?

**Comment by TheElegantCoding** [comment]
thanks that work and also i find an error in my config, in order to work inside all the repo i have to put `files: [ '**/*.html' ]`

Other problem i have with eslint flat config is the type in typescript my config is in typescript

```js
import { htmlDisabledRule } from '@module/html/rule/html_disabled_rule';
import { htmlGeneralRule } from '@module/html/rule/html_general_rule';
import pluginHtml from "@html-eslint/eslint-plugin";
import parserHtml from "@html-eslint/parser";


const html =
{
  files: [ '**/*.html' ],
  languageOptions:
  {
    parser: parserHtml
  },
  plugins:
  {
    html: pluginHtml
  },
  rules: {
    ...htmlGeneralRule,
    ...htmlDisabledRule
  }
};
export { html };
```

in the `pluginHtml` import i get this error `Could not find a declaration file for module '@html-eslint/eslint-plugin'.`

**Comment by yeonjuan** [comment]
> in the pluginHtml import i get this error Could not find a declaration file for module '@html-eslint/eslint-plugin'.

@TheElegantCoding Thank you. I think this should be fixed..!

**Comment by LatenPath** [comment]
@yeonjuan  Dear sir, I got this warning when import `recommended` setting.
![image](https://github.com/yeonjuan/html-eslint/assets/145383056/added541-aa9a-4de1-8f0f-9c1804a6ad2a)

> Hi @TheElegantCoding, Thanks for the report!. Is there anything else we need to do to support flat config?
> 
> I've tested the config below and it seems to be working fine, did you run into any issues?
> 
> ```js
> const Plugin = require("@html-eslint/eslint-plugin");
> const Parser = require("@html-eslint/parser");
> 
> module.exports = [
>   {
>     plugins: { "@html-eslint": Plugin },
>     languageOptions: {
>       parser: Parser,
>     },
>     files: ["*.html"],
>     rules: {
>       //...
>     },
>   },
> ];
> ```

Eslint still working fine even error output.
![image](https://github.com/yeonjuan/html-eslint/assets/145383056/d53aa9b3-33fc-4040-8439-f8018b411b63)

Please help me 😢

**Comment by yeonjuan** [comment]
Hi @LatenPath , Could you try `pluginHtml.configs.recommended.rules` instead of `pluginHtml.configs.recommended`?

```
const pluginHtml = require("@html-eslint/eslint-plugin");
const parserHtml = require("@html-eslint/parser");

module.exports = [
  {
    files: ["**/*.html"],
    languageOptions: {
      parser: parserHtml,
    },
    plugins: {
      "@html-eslint": pluginHtml,
    },
    rules: pluginHtml.configs.recommended.rules,
  },
];

```

**Comment by LatenPath** [comment]
@yeonjuan It's work, sir! 
![image](https://github.com/yeonjuan/html-eslint/assets/145383056/e682f9c5-8c32-4690-aa55-9d5328d954a2)

Disable rule/ Auto-fix,... also work fine!

![image](https://github.com/yeonjuan/html-eslint/assets/145383056/ecab148f-daac-4857-a4f6-04355cc9749f)

Thank you so much!

**Comment by yeonjuan** [comment]
Hi @TheElegantCoding @LatenPath 
new version is released. html-eslint supports flat config now! Thanks for the reporting issue!
- https://html-eslint.org/docs/getting-started#flat-config
