### ISSUE TITLE
lowercase rule should be able to ignore specific attributes

### ISSUE THREAD

**Issue by ChristopherBull** [yeonjuan/html-eslint#177]
The [lowercase rule](https://html-eslint.org/docs/rules/lowercase) enforces all tags and attributes to be lowercase. However, some attributes are meant to be case-sensitive (or camel-cased).

For example, the [`viewBox`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) SVG attribute should be ignored by this rule by default--it should not be lowercase.

This could be achieved similarly to: https://htmlhint.com/docs/user-guide/rules/attr-lowercase

**Comment by yeonjuan** [comment]
Hi @ChristopherBull Thank you for reporting the issue. This is definitely a bug and should be fixed.
