### ISSUE TITLE
Add support for regexp flags in id-naming-convention rule

### ISSUE THREAD

**Issue by jdussouillez** [yeonjuan/html-eslint#180]
It would be nice to support regexp flags in the `id-naming-convention` rule.

This is not a priority feature but a nice to have.

I think there are different implementations possible :
- Add a `flags` parameter and keeping `pattern`
- Change the `pattern` option to `regex` with type `RegExp` instead of `string` :warning: breaks compatibility
- Keep the `pattern` option but accept both `string` and `RegExp` values

I opened https://github.com/yeonjuan/html-eslint/pull/181 with the first solution. Feel free to modify/reject it.

----

BTW, it would be nice to have a very short "how to contribute" block in the readme, especially with the NPM scripts (Something like "before submitting PRs, run `npm run format && npm run build && npm run lint && npm run test`").

**Comment by yeonjuan** [comment]
@jdussouillez Thanks for the suggestion, Agree!

> BTW, it would be nice to have a very short "how to contribute" block in the readme, especially with the NPM scripts (Something like "before submitting PRs, run npm run format && npm run build && npm run lint && npm run test").

Nice! I made a new issue for it. (https://github.com/yeonjuan/html-eslint/issues/182)

**Comment by yeonjuan** [comment]
Hi @jdussouillez Just a heads up. I'm planning to release a merged version this weekend.

**Comment by jdussouillez** [comment]
Hi, OK thanks!
