### ISSUE TITLE
Add guidance on how to lint JavaScript inside HTML files

### ISSUE THREAD

**Issue by dandv** [yeonjuan/html-eslint#199]
From a quick look at this project, it appears it only lints HTML, and doesn't pass through the JavaScript in `<script>` tags to ESLint.

Whether that is correct or not, I think it would help to add a note to the README and to [the homepage](https://html-eslint.org/) about how to lint JavaScript in HTML files.

**Comment by yeonjuan** [comment]
@dandv Thanks for reporting this issue. 
> From a quick look at this project, it appears it only lints HTML, and doesn't pass through the JavaScript in <script> tags to ESLint.
Yes, this plugin cannot lint javascript in a `script`. It would be nice to mention in the documentation to use [eslint-plugin-html](https://github.com/BenoitZugmeyer/eslint-plugin-html) for linting js inside scripts.
