### ISSUE TITLE
[Feature request] Tests that incorporate multiple rules, to make sure they don't conflict

### ISSUE THREAD

**Issue by RobertAKARobin** [yeonjuan/html-eslint#203]
It might be nice if the html-eslint repo included tests that supported multiple rules, or a whole `.eslintrc`. This would help us make sure rules don't conflict with each other.

It would also be nice if these tests could be run against a separate `.html` file, as opposed to needing to paste the code as `{ code: "" }` inside a `.test.js` file.

For example, as part of html-eslint's test suite, I'd love to be able to test the complete HTML of a sample webpage with a specific `.eslintrc` configuration and make sure that it throws the expected linting errors.

I'm more than happy to contribute some of these tests myself, just first want @yeonjuan's guidance on where in the repo to put them and how to structure them so that it aligns with his vision. Thanks! :)

**Comment by yeonjuan** [comment]
Hi @RobertAKARobin Thanks for the suggestion! 👍 👍 
What do you think about creating a new directory in the root for the tests?
```
/
 |- /tests
     |- /[test-name]
        |-  /.eslintrc
        |-  /.source.html
```
If you already have a structure in mind, we'd love to hear about it!

**Comment by RobertAKARobin** [comment]
@yeonjuan Sounds fine by me. I just noticed `/integration-test-projects`. Is that intended for something like this?

**Comment by yeonjuan** [comment]
@RobertAKARobin 
`/integration-test-projects` is a directory for testing compatibility with eslint versions. You can use this as it is or create a new directory. 👍
