### ISSUE TITLE
lintText Usage Error

### ISSUE THREAD

**Issue by natoen** [yeonjuan/html-eslint#221]
Hello. I am sorry for disturbing.

I am stuck here for quite a while. The below is throwing this error:
`Error: ESLint configuration in BaseConfig is invalid:
	- Unexpected top-level property "languageOptions".`

I have exhausted other tries by putting parser on top for example. [I am confident that this works with eslint-html-plugin as well](https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/293) as written in your docs. I would appreciate any help for this. Thank you very much for giving the world html-eslint!

```javascript
const { ESLint } = require("eslint");
const html = require("eslint-plugin-html");
const htmlEslint = require('@html-eslint/eslint-plugin');
const PARSER_HTML = require('@html-eslint/parser');

const srcCode = `<img src="https://www.facebook.com/tr?id={pixel-id}&ev={standard-event}" height="1" width="1" style="display:none"/>`;

(async function() {
  const eslint = new ESLint({
    baseConfig: {
      languageOptions: {
        parser: PARSER_HTML
      },
    },
    plugins: {
      html,
      "@html-eslint": htmlEslint,
    },
  });

  const results = await eslint.lintText(srcCode);
  console.log(results);
})().catch((error) => {
  process.exitCode = 1;
  console.error(error);
});
```

**Comment by yeonjuan** [comment]
@natoen Can we know the version of eslint you are using? It would be great if you could share a reproducible github repository.

**Comment by natoen** [comment]
@yeonjuan Thank you very much for replying. I made a repo here that you can run. Please check. Thank you!

https://github.com/natoen/html-eslint-issue-221/blob/master/README.md

**Comment by natoen** [comment]
github.com/natoen/html-eslint-issue-221

**Comment by natoen** [comment]
www.github.com/natoen/html-eslint-issue-221

**Comment by yeonjuan** [comment]
Hi @natoen I apologize for the delay in responding. I'm not familiar with the ESLint Node API, so I'm not sure I know the right solution.
I found it worked when I did the following

1. Update eslint version to 9.12.0

2. Run below code.

```ts
const { ESLint } = require("eslint");
const htmlEslint = require('@html-eslint/eslint-plugin');
const htmlEslintParser = require('@html-eslint/parser');

const sourceCode = `<img src="https://www.facebook.com/tr?id={pixel-id}&ev={standard-event}" height="1" width="1" style="display:none"/>`;

(async function() {
  const eslint = new ESLint({
    overrideConfigFile: true,
    baseConfig: [
      {
        plugins: {
          '@html-eslint': {
            rules:  htmlEslint.rules,
          }
        },
        files: ["**/*.html"],
        languageOptions: {
          parser: htmlEslintParser,
        },
        rules: {
          '@html-eslint/require-img-alt': 'error'
        }
      }
    ],
  });
  const lintResult = (await eslint.lintText(sourceCode, {
    // this is needed to work but this file does not exist
    // https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/294
    filePath: "placeholder.html",
  }))[0];

  console.log(lintResult);
})().catch((error) => {
  process.exitCode = 1;
  console.error(error);
});

```

3. result

```
{
  filePath: '.../html-eslint-issue-221/placeholder.html',
  messages: [
    {
      ruleId: '@html-eslint/require-img-alt',
      severity: 2,
      message: 'Missing `alt` attribute at `<img>` tag',
      line: 1,
      column: 1,
      nodeType: null,
      messageId: 'missingAlt',
      endLine: 1,
      endColumn: 117
    }
  ],
  suppressedMessages: [],
  errorCount: 1,
  fatalErrorCount: 0,
  warningCount: 0,
  fixableErrorCount: 0,
  fixableWarningCount: 0,
  source: '<img src="https://www.facebook.com/tr?id={pixel-id}&ev={standard-event}" height="1" width="1" style="display:none"/>',
  usedDeprecatedRules: [Getter]
}
```

I don't think this is an html-eslint specific question, perhaps if you ask the eslint project community you'll find a more accurate solution. 

Thanks! 👍

**Comment by natoen** [comment]
@yeonjuan Thank you very much for replying so fast. This saved us. Thank you for taking the time. I am wondering how may I put this in your README since I am sure we are not the only one finding for this. Let me close this. I am sorry for my late answer!
