### ISSUE TITLE
Which rules do or don't work?

### ISSUE THREAD

**Issue by B34v0n** [yeonjuan/html-eslint#222]
I just found this and was happy, that something like this exists.

I tried to implement some rules in my app and none of it led to errors in linting.

Then I tried the playground and even there, some rules just don't apply.

![{3F594020-DCB2-428C-B8F0-F7B0374741D0}](https://github.com/user-attachments/assets/cdec9df1-4908-4793-846b-d9de3f1cf890)

In the screenshot there should be multiple errors, like "newline after Elements", "id doesn't match convention" and i guess also "newline after attributes".

Now I wonder, if I did something wrong or why these rules do not apply.
Can you help me with that?

**Comment by yeonjuan** [comment]
Hi, @B34v0n. Thanks for the report. The playground was out of date. I just deployed to the latest version, would you like to check again?
- https://html-eslint.org/playground#eyJjb2RlIjoiPCFET0NUWVBFIGh0bWw+XG48aHRtbD5cbiAgICA8aGVhZD5cbiAgICA8L2hlYWQ+XG4gICAgPGJvZHk+XG4gICAgICAgIDxkaXYgaWQ9XCJ0ZXN0LWlkXCIgY2xhc3M9XCJ0ZXN0MlwiIHN0eWxlPVwiYmFja2dyb3VuZDpyZWQ7XCI+IDxsaT4gZm9vIDwvbGk+IDwvZGl2PlxuICAgIDwvYm9keT5cbjwvaHRtbD5cbiIsImNvbmZpZ3MiOiJ7XG4gIFwicnVsZXNcIjoge1xuICAgIFwiQGh0bWwtZXNsaW50L2luZGVudFwiOiBcImVycm9yXCIsXG4gICAgXCJAaHRtbC1lc2xpbnQvYXR0cnMtbmV3bGluZVwiOiBbXCJlcnJvclwiLCB7XCJpZkF0dHJzTW9yZVRoYW5cIjogMiB9XSxcblx0XCJAaHRtbC1lc2xpbnQvaWQtbmFtaW5nLWNvbnZlbnRpb25cIjogW1wiZXJyb3JcIiwgXCJQYXNjYWxDYXNlXCJdXG4gIH1cbn0ifQ==
<img width="1678" alt="스크린샷 2024-10-23 오전 9 30 48" src="https://github.com/user-attachments/assets/a03c5d4f-a52c-402d-953e-8c4832372eb6">

**Comment by B34v0n** [comment]
Hi @yeonjuan, my desired rules now work in the playground, thank you.
The problem in my project comes from it being angular and needing another parser. I found some posts and issues, which tackle that topic. So I close this issue and need to find a solution in my app. Thanks. :)
