### ISSUE TITLE
Strange Auto-Fix with @html-eslint/element-newline when missing a closing tag

### ISSUE THREAD

**Issue by ricealexander** [yeonjuan/html-eslint#30]
When a closing tag is missing, element-newline may add many extra lines.

I am using the recommended configuration:
<details open>
<summary>.eslintrc.js</summary>
<br>

```js
module.exports = {
  plugins: ['@html-eslint'],
  overrides: [
    {
      files: ['*.html'],
      parser: '@html-eslint/parser',
      'extends': ['plugin:@html-eslint/recommended'],
    },
  ],
}
```

</details>

An example, the first li tag is missing its closing tag:

```html
<!DOCTYPE html>
<html lang="en">
    <body>
        <ul>
            <li>Item Here
            <li>Second Item Here</li>
        </ul>
    </body>
</html>
```

Auto-fixes to:
```
<!DOCTYPE html>
<html lang="en">
    <body>
        <ul>
            <li>Item Here











<li>Second Item Here</li>
        </ul>
    </body>
</html>
```

Continued autofixes add more and more empty lines.

**Comment by yeonjuan** [comment]
@ricealexander Thanks for reporting and your interest in this project:) 
There was a bug and I made a PR to fix it :)  - #32.
