### ISSUE TITLE
new rule: noDuplicateAttrs

### ISSUE THREAD

**Issue by Plondrein** [yeonjuan/html-eslint#49]
I'm trying to migrate to your awesome plugin, but I can't find this rule implemented

[ref](https://htmlhint.com/docs/user-guide/rules/attr-no-duplication)

**Comment by yeonjuan** [comment]
@Plondrein Thanks for your suggestion.😀 It would be great if we can add that rule. I'll work on it when I have time.

**Comment by Plondrein** [comment]
I tried to implement myself, but it seems that parse5 is filtering out duplicated attributes so it might not be that easy :(

**Comment by yeonjuan** [comment]
@Plondrein Yes. you are right. I think we should change the parser. Maybe [angular-eslint-parser](https://github.com/angular-eslint/angular-eslint) is suitable for this project.

**Comment by Plondrein** [comment]
Would be awesome cause i figured out another issue, I cant use angular-eslint-plugin and yours at the same time because of different parsers

**Comment by yeonjuan** [comment]
Hi @Plondrein I finished changing the parser in https://github.com/yeonjuan/html-eslint/pull/51.

Now, we can handle duplicate attributes 😀.

```html
<div foo="foo1" foo="foo2"></div>
```


- generated AST
```json
{
   type: "Div",
   attrs: [ 
      {
         name: "foo",
         value: "foo1",
          // ...
      },
      {
         name: "foo",
         value: "foo2"
         // ...
      }
   ],
   //...
}
```
