### ISSUE TITLE
Conflict with eslint rule "spaced-comment"

### ISSUE THREAD

**Issue by ClementMindflow** [yeonjuan/html-eslint#67]
When a HTML comment is parsed using `html-eslint` it produce comment node of type `comment`.
If that node is given to the eslint builtin `spaced-comment` rule, it will fail with the following error:

```
TypeError: Cannot read property 'markers' of undefined
Occurred while linting /Users/clement/Dev/mindflow-platform/apps/studio/public/index.html:1
    at checkCommentForSpace (/Users/clement/Dev/mindflow-platform/node_modules/eslint/lib/rules/spaced-comment.js:336:49)
    at /Users/clement/Dev/mindflow-platform/node_modules/eslint/lib/rules/spaced-comment.js:385:19
...
```

After a quick look at the code, it seems like the `spaced-comment` rule expect comment node to have the `type` attribute set to either `block` or `line`, and node `comment` ( see [here](https://github.com/eslint/eslint/blob/f113cdd872257d72bbd66d95e4eaf13623323b24/lib/rules/spaced-comment.js#L251) )

Maybe setting the node type to the appropriate type would fix the issue ...

**Comment by yeonjuan** [comment]
Hi @ClementMindflow   Sorry for being late.

html-eslint does not work with ECMAScript AST, It uses a AST made from `html-eslint/parser`.
It means we cannot use common eslint rules with html-eslint because the targeting language is different.

- eslint: `ECMAScript, JSX`,
- html-eslint: `HTML`

I think It would be great if we add a new `spaced-comment` rule which supporting HTML.
Thanks for the report 👍

**Comment by galyfray** [comment]
it seems that any rules that has to do with comments cause troubles. I have a similar issue with the `capitalized-comments` rule

**Comment by FatehAK** [comment]
Fixed it temporarily by turning off the 'space-comments' rule for *.html alone in overrides key. Is there a way to permanently fix this?

**Comment by yeonjuan** [comment]
@FatehAK For permanently fixing it we should create a new rule (ie: `@html-eslint/space-comments`) which can handle html syntax.

**Comment by howieye** [comment]
This bug still exists today.

**Comment by yeonjuan** [comment]
This is not a bug, it's a misconfiguration. The comment-related rules that apply to JS rules should not be used in HTML files.
If anyone run into similar issues, try turning off the comment-related rules for html. I think this should be added to the configuration documentation.

```js
{
  files: ["**/*.html"],
    rules: {
       "spaced-comment": "off"
    },
}
```
