### ISSUE TITLE
Bug: @html-eslint/require-closing-tags

### ISSUE THREAD

**Issue by TP-O** [yeonjuan/html-eslint#73]
I have provide closing tag, but `@html-eslint/require-closing-tags` keeps giving error.

![image](https://user-images.githubusercontent.com/53143403/140746560-9c61234a-4dc0-481d-ae8b-3c4f32792e04.png)

**Comment by yeonjuan** [comment]
@TP-O  Thanks for the reporting :) . I can reproduce it. ( [demo](https://yeonjuan.github.io/html-eslint/playground#eyJjb2RlIjoiPCFET0NUWVBFIGh0bWw+XG48aHRtbD5cbiAgICA8aGVhZD5cbiAgICA8L2hlYWQ+XG4gICAgPGJvZHk+XG4gICAgICA8c3ZnIHZpZXdCb3g9XCIwIDAgMTAgMTBcIiB4bWxucz1cImh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnXCI+XG4gIDxkZWZzPlxuICAgIDxsaW5lYXJHcmFkaWVudCBpZD1cIm15R3JhZGllbnRcIiBncmFkaWVudFRyYW5zZm9ybT1cInJvdGF0ZSg5MClcIj5cbiAgICA8L2xpbmVhckdyYWRpZW50PlxuICA8L2RlZnM+XG48L3N2Zz5cbiAgICA8L2JvZHk+XG48L2h0bWw+XG4iLCJydWxlcyI6eyJAaHRtbC1lc2xpbnQvaW5kZW50Ijoib2ZmIiwiQGh0bWwtZXNsaW50L3JlcXVpcmUtbGktY29udGFpbmVyIjoib2ZmIiwiQGh0bWwtZXNsaW50L3JlcXVpcmUtY2xvc2luZy10YWdzIjoiZXJyb3IifX0=) ). I'll work on this as soon.
