### ISSUE TITLE
Feature -- Prevents a attribute to be used

### ISSUE THREAD

**Issue by iagojsilva** [yeonjuan/html-eslint#74]
It will be nice if we had a rule to prevents a attribute to be used. For example:

#### my-page.hmtl
```html
<input type="text" data-cy="input">
```
#### .eslintrc.json
```ts
"restricted-attributes": [
	"error",
	{
		"attrs": [
			{ "name": "data-cy", "message": "data-cy is deprecated use data-test instead" },
		]
	}
],
```

### let me know if you guys need more information

**Comment by yeonjuan** [comment]
> It will be nice if we had a rule to prevents a attribute to be used

@iagojsilva Thanks for the suggestion. I agree 👍
