### ISSUE TITLE
require-closing-tags does not allow foreign elements like svg to self close

### ISSUE THREAD

**Issue by NikhilJohnB** [yeonjuan/html-eslint#75]
False positives for Foreign elements like svg namespace in rule '_require-closing-tags_'.

As mentioned in [https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements](url) , they are allowed to self close.
Examples of such are also visible in [https://www.w3schools.com/html/html5_svg.asp](url)

Please do look into the issue. Attaching a example of a false positive:
![image](https://user-images.githubusercontent.com/93919688/141261361-e36d35df-0f74-4dd8-8fae-ba75138ff7d4.png)

**Comment by yeonjuan** [comment]
@NikhilJohnB  Thanks for the reporting 👍 . I'll fix as soon

**Comment by NikhilJohnB** [comment]
Thank you for the response. Your project is really great! :)
