### ISSUE TITLE
Bug: @html-eslint/indent

### ISSUE THREAD

**Issue by alexei-vedder** [yeonjuan/html-eslint#79]
"indent" rule shows that there should be indentation when it's the first line in HTML file:

![Screenshot 2021-11-21 at 16 14 07](https://user-images.githubusercontent.com/51241875/142761412-644169c2-ce59-439f-a2d3-48fb0224e396.png)

After letting ESLint fix the problem, it goes this weird way:

![Screenshot 2021-11-21 at 16 20 57](https://user-images.githubusercontent.com/51241875/142761551-a8398be5-328b-46fe-beae-d46e3e1379da.png)

Maybe this thing happens because the rule expects an "html" tag in the beginning for the file, but it's an Angular template and this file should be considered as correct one. For index.html, which does have "html" tag in the beginning, the rule works fine.

**Comment by yeonjuan** [comment]
@alexei-vedder Thanks for the reporting. I can reproduce it ([demo](https://yeonjuan.github.io/html-eslint/playground#eyJjb2RlIjoiPGRpdiBjbGFzcz1cImZvb1wiPlxuICAgIDxkaXY+XG4gICAgICAgIHt7dGVtcGxhdGV9fVxuICAgIDwvZGl2PlxuPC9kaXY+IiwicnVsZXMiOnsiQGh0bWwtZXNsaW50L2luZGVudCI6ImVycm9yIiwiQGh0bWwtZXNsaW50L3JlcXVpcmUtbGktY29udGFpbmVyIjoib2ZmIiwiQGh0bWwtZXNsaW50L3JlcXVpcmUtY2xvc2luZy10YWdzIjoib2ZmIn19)) I'll fix it as soon.

**Comment by alexei-vedder** [comment]
Thanks a lot for the fix and for the plugin in general!
