### ISSUE TITLE
custom rules for html elements like tr, td, th do not work unless parent element table is present

### ISSUE THREAD

**Issue by NikhilJohnB** [yeonjuan/html-eslint#80]
The custom rules that is written for the elements tr, td, th do not work unless parent element table is present.
Please find the attached screenshots:
![image](https://user-images.githubusercontent.com/93919688/142857095-d1da4056-8801-4a2a-8e0f-a9cc620c6b72.png)
![image](https://user-images.githubusercontent.com/93919688/142857163-4a0b1931-8ad6-4866-a3f3-37c75d53d1db.png)

Is this the desired behavior in such cases?

**Comment by yeonjuan** [comment]
> The custom rules that is written for the elements tr ...
 
Hi @NikhilJohnB  :) What the `custom rules` mean?

**Comment by NikhilJohnB** [comment]
Hi @yeonjuan , sorry for not being clear. I am trying out to form my own rules in addition to the standard ones provided in you project. So those rules that I have formulated by myself is what I have meant by 'custom rules'.

**Comment by yeonjuan** [comment]
@NikhilJohnB html-eslint's parser based on `parse5` which parse quite strictly follow html spec. I assume that is whay your custom rule didnt work well. I think html-eslint parser should parser less strictly.

**Comment by NikhilJohnB** [comment]
Thank you for the update. Shall I close this open issue?

**Comment by yeonjuan** [comment]
@NikhilJohnB Sure i'll closed it
