### ISSUE TITLE
Preserve single space before self-closing tag

### ISSUE THREAD

**Issue by MorevM** [yeonjuan/html-eslint#90]
Hello!

I noticed that rule `@html-eslint/no-extra-spacing-attrs` reports if there a space before self-closing tag.

![no-extra-spacing](https://user-images.githubusercontent.com/49679666/155842105-cb40de1f-529d-4cb1-bbd4-8ee35ae37ec4.jpg)

I think it's more comfortable to be able to customize this behavior. 
Maybe it's a personal issue, but the rule is in the "style" category, so guess it should be configurable to fit any preferences. 

Maybe this can be covered in separate rule because it's also related to this case in terms of `style`: 

![no-reports](https://user-images.githubusercontent.com/49679666/155842118-5469d154-145a-492b-a6a2-c3a0dbec1844.jpg)

What do you think? Can we implement it? How can I help?

**Comment by yeonjuan** [comment]
@MorevM  Thanks for the report. :)

> Maybe this can be covered in separate rule 

I agree. It would be nice if we can handle it.
What about a new general rule `no-extra-spacing`  which check all extra spaces not only around attributes? Then we can deprecate `no-extra-spacing-attrs`

**Comment by MorevM** [comment]
@yeonjuan yes, such new rule looks good to me with parameter `{ spaceBeforeSelfClosing: boolean }` or similar.

* I'm not familiar with the ESLint API for plugin developers. 
While this looks interesting to dig into, I'm a little limited on time so I can't seem to get it done before a week or even two if you don't have time to do it before. :)

**Comment by yeonjuan** [comment]
@MorevM  Sure, :)  please let me know if you can't take any time to do it. Then I'll take it. 👍

**Comment by penghouho** [comment]
I tried to off this rule by 
 "@html-eslint/no-extra-spacing-attrs": "off",
 
 but it is still report them as errors.
