### ISSUE TITLE
[Feature suggestion] Sorting html attributes

### ISSUE THREAD

**Issue by neviaumi** [yeonjuan/html-eslint#92]
When working react projects, i have eslint rule below
[sort-props](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-sort-props.md)

It is possible include similar rule in this plugin ? 

The reason of this rules:
1. More easily to prevent conflict

**Comment by yeonjuan** [comment]
@davidNHK Thanks for the suggestion, I agree. I think we can implement it 👍

**Comment by zerowww** [comment]
Hello @yeonjuan, any update on this ?

**Comment by yeonjuan** [comment]
Hi, @zerowww Nothing has been done. In the meantime, something else has been done. This issue will be proceeded in the future.

**Comment by yeonjuan** [comment]
Hi, @zerowww @neviaumi  . It took a long time due to my personal schedule. [@html-eslint/sort-attrs]( https://github.com/yeonjuan/html-eslint/blob/main/docs/rules/sort-attrs.md) rule has been added in v0.21.0. Thanks for the nice feedback.
